---
kind: Pod
apiVersion: v1
metadata:
  name: collector-app
  labels:
    app: collector
spec:
  containers:
    - name: collector-app
      image: docker.io/library/collector-app-img
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: collector-service
spec:
  selector:
    app: collector
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: collector-http
---