kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sunil.kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 8181
    hostPort: 8181
    protocol: TCP
  - containerPort: 8282
    hostPort: 8282
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP