---
kind: Pod
apiVersion: v1
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  containers:
    - name: todo-app
      image: docker.io/library/todo-app-img
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: todo-http
---