kind: Pod
apiVersion: v1
metadata:
  name: go-todo
  labels:
    app: go-todo
spec:
  containers:
  - name: go-todo
    image: docker.io/library/go-todo-img
    imagePullPolicy: Never
    ports:
    - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: go-todo
spec:
  type: NodePort
  ports:
  - name: http
    port: 8181
  selector:
    app: go-todo