---
kind: Pod
apiVersion: v1
metadata:
  name: collector-app
  labels:
    app: collector
spec:
  containers:
    - name: collector-app
      image: docker.io/library/collector-app-img
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: collector-service
spec:
  selector:
    app: collector
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: collector-http
---
kind: Pod
apiVersion: v1
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  containers:
    - name: todo-app
      image: docker.io/library/todo-app-img
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: todo-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collector-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /todos
            backend:
              service:
                name: todo-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /api(/|$)(.*)
            backend:
              service:
                name: collector-service
                port:
                  number: 8080
---
